apiVersion: v1
kind: Pod
metadata:
  name: nginx-slctr
  labels:
    env: nginx-slctr
spec:
  containers:
  - name: nginx-slctr
    image: nginx:1.15
    imagePullPolicy: IfNotPresent
  nodeSelector:
    type: dev